services:
  sxng-proxy:
    build: ./proxy
    container_name: sxng-proxy
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - PROXY_URL=${PROXY_URL:-}
      - BRAVE_PROFILE_0=/data/brave_profile_0
      - BRAVE_PROFILE_1=/data/brave_profile_1
      - BRAVE_PROFILE_2=/data/brave_profile_2
      - STARTUP_IDLE_SECONDS=${STARTUP_IDLE_SECONDS:-0}
    volumes:
      - ./data/brave_profile_0:/data/brave_profile_0:z
      - ./data/brave_profile_1:/data/brave_profile_1:z
      - ./data/brave_profile_2:/data/brave_profile_2:z
      - ./proxy/app:/app/app:z
    profiles:
      - standard
      - warp
    networks:
      - searxng-net

  searxng-warp:
    image: docker.io/caas/warp-socks:latest
    container_name: searxng-warp
    restart: unless-stopped
    ports:
      - "127.0.0.1:1080:9091"
    profiles:
      - warp
    networks:
      - searxng-net

networks:
  searxng-net:
    external: true
    name: ${EXTERNAL_NETWORK:-searxng-net}
